import type { SigmaRule } from "./types";

export const SIGMA_RULES: SigmaRule[] = [
  {
    id: "SIG-001",
    title: "SSH Brute Force Attempt",
    description: "Multiple failed password attempts for the same or invalid user from a single source within a short window.",
    severity: "High",
    mitreId: "T1110.001",
    mitreName: "Brute Force: Password Guessing",
    tactic: "Credential Access",
    eventType: "SSH Brute Force",
    status: "active",
    logsource: "linux/sshd",
  },
  {
    id: "SIG-002",
    title: "SSH Authentication Failure",
    description: "Single failed SSH password or public-key authentication event.",
    severity: "Low",
    mitreId: "T1110",
    mitreName: "Brute Force",
    tactic: "Credential Access",
    eventType: "SSH Auth Failure",
    status: "active",
    logsource: "linux/sshd",
  },
  {
    id: "SIG-003",
    title: "Web Path Traversal Attempt",
    description: "HTTP request containing directory traversal sequences (../ or encoded variants) targeting sensitive files.",
    severity: "Critical",
    mitreId: "T1190",
    mitreName: "Exploit Public-Facing Application",
    tactic: "Initial Access",
    eventType: "Path Traversal",
    status: "active",
    logsource: "webserver/access",
  },
  {
    id: "SIG-004",
    title: "SQL Injection Pattern in URI",
    description: "Detects UNION SELECT, tautologies, comment sequences and stacked queries inside request URIs.",
    severity: "Critical",
    mitreId: "T1190",
    mitreName: "Exploit Public-Facing Application",
    tactic: "Initial Access",
    eventType: "SQL Injection",
    status: "active",
    logsource: "webserver/access",
  },
  {
    id: "SIG-005",
    title: "Web Application Fuzzing / Scanner",
    description: "Known scanner user-agents (nikto, sqlmap, gobuster, ffuf) or high-rate 404 bursts for admin/config paths.",
    severity: "Medium",
    mitreId: "T1595.003",
    mitreName: "Active Scanning: Wordlist Scanning",
    tactic: "Reconnaissance",
    eventType: "Web Fuzzing",
    status: "active",
    logsource: "webserver/access",
  },
  {
    id: "SIG-006",
    title: "UFW Inbound Block",
    description: "Firewall dropped an inbound packet on a monitored port.",
    severity: "Low",
    mitreId: "T1046",
    mitreName: "Network Service Discovery",
    tactic: "Discovery",
    eventType: "Firewall Drop",
    status: "active",
    logsource: "linux/ufw",
  },
  {
    id: "SIG-007",
    title: "Horizontal Port Scan",
    description: "Single source hitting many distinct destination ports blocked by the firewall.",
    severity: "Medium",
    mitreId: "T1046",
    mitreName: "Network Service Discovery",
    tactic: "Discovery",
    eventType: "Port Scan",
    status: "active",
    logsource: "linux/ufw",
  },
  {
    id: "SIG-008",
    title: "Sudo Privilege Escalation",
    description: "sudo invocation to root shell or authentication failure indicating escalation attempt.",
    severity: "High",
    mitreId: "T1548.003",
    mitreName: "Abuse Elevation Control: Sudo",
    tactic: "Privilege Escalation",
    eventType: "Privilege Escalation",
    status: "active",
    logsource: "linux/auth",
  },
  {
    id: "SIG-009",
    title: "Outbound C2 Beacon Signature",
    description: "Periodic outbound connections to known C2 infrastructure or DGA-like domains.",
    severity: "Critical",
    mitreId: "T1071.001",
    mitreName: "Application Layer Protocol: Web Protocols",
    tactic: "Command and Control",
    eventType: "Malware Beacon",
    status: "experimental",
    logsource: "proxy/outbound",
  },
  {
    id: "SIG-010",
    title: "Successful Login After Brute Force",
    description: "Accepted SSH login from a source that recently generated brute-force alerts.",
    severity: "Critical",
    mitreId: "T1078",
    mitreName: "Valid Accounts",
    tactic: "Defense Evasion",
    eventType: "Successful Login",
    status: "active",
    logsource: "linux/sshd",
  },
];

export const ruleByType = (t: SigmaRule["eventType"]) => SIGMA_RULES.find((r) => r.eventType === t);
